// Generated by Wrangler on Thu Jun 06 2024 15:20:40 GMT-0700 (Pacific Daylight Time)
// by running `wrangler types`

interface Env {
	DEV: false;
	API_KEY: string;
	GOOGLE_AUTH_JWK: string;
	GOOGLE_AUTH: string;
	SHEET_ID: string;
}
