// Generated by Wrangler on Thu Jun 06 2024 13:45:25 GMT-0700 (Pacific Daylight Time)
// by running `wrangler types`

interface Env {
	API_KEY: string;
	GOOGLE_AUTH_JWK: string;
	GOOGLE_AUTH: string;
	SHEET_ID: string;
}
